sequenceDiagram
    buyer->>react ambassador: Access to reactambassador.com/register
    react ambassador->>buyer: Render register form
    buyer->>react ambassador: Fill form and press Submit button
    react ambassador->>api gateway: POST backend.com/register
    api gateway->>user microservice: POST user.com/register
    user microservice->>user db: save user
    user db->>user microservice: return user saved
    user microservice->>+circuit breaker: POST circuitbreaker.com/user
    alt is open state
        circuit breaker->>-user microservice: return error response
    else is closed | half open
        circuit breaker->>+auth microservice: POST auth.com/user
        alt is timeout
            circuit breaker->>user microservice: return error response
        else is not timeout
            auth microservice->>auth db: save lite user
            auth db->>auth microservice: return lite user saved
            auth microservice->>circuit breaker: return lite user saved
            circuit breaker->>user microservice: return lite user saved
        end
    end
    user microservice->>api gateway: return response
    api gateway->>react ambassador: return response
    alt creaded successfully
        react ambassador->>buyer: redirect reactambassador.com/login
    else is error
        react ambassador->>buyer: render error message
    end
